export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/products";
export * from "@/pages/dashboard/orders";
export * from "@/pages/dashboard/invoice";
export * from "@/pages/dashboard/register";
export * from "@/pages/dashboard/users";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
